<?php

return [
    ['class', 'stranger', 'door', 'male'],
    ['class', 'stranger', 'door', 'male'],
    ['class', 'stranger', 'door', 'female'],
    ['class', 'stranger', 'door', 'male'],
    ['class', 'paladin', 'door', 'male'],
    ['class', 'paladin', 'door', 'female'],
    ['class', 'paladin', 'door', 'male'],
    ['class', 'paladin', 'door', 'male'],
    ['class', 'raider', 'door', 'male'],
    ['class', 'raider', 'door', 'male'],
    ['class', 'raider', 'door', 'male'],
    ['class', 'raider', 'door', 'female'],
    ['class', 'scientist', 'door', 'male'],
    ['class', 'scientist', 'door', 'male'],
    ['class', 'scientist', 'door', 'female'],
    ['class', 'scientist', 'door', 'male'],
    ['door', 'trap'], ['door', 'trap'], ['door', 'trap'], ['door', 'trap'],
    ['door', 'trap'], ['door', 'trap'], ['door', 'trap'], ['door', 'trap'],
    ['door', 'trap'], ['door', 'trap'], ['door', 'trap'], ['door', 'trap'], ['door', 'trap'],
    ['monster', 'door'], ['monster', 'alien', 'door'], ['monster', 'swamp', 'door'], ['monster', 'gul', 'door'],
    ['monster', 'ant', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'robot', 'door'],
    ['monster', 'door'], ['monster', 'gul', 'door'], ['monster', 'door'], ['monster', 'door'], ['monster', 'door'],
    ['monster', 'door'], ['monster', 'claw', 'door'], ['monster', 'claw', 'door'], ['monster', 'swamp', 'door'],
    ['monster', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'ant', 'door'], ['monster', 'door'], ['monster', 'door'],
    ['monster', 'ant', 'door'], ['monster', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'],
    ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'door'],
    ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'robot', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'robot', 'door'], ['monster', 'gul', 'door'], ['monster', 'door'],
    ['monster', 'mutant', 'door'], ['monster', 'mutant', 'door'], ['monster', 'mutant', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'],
    ['monster', 'alien', 'door'], ['monster', 'swamp', 'door'], ['monster', 'door'], ['monster', 'door'],
    ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'],
    ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['vats', 'door'], ['vats', 'door'],
    ['stray', 'door'], ['stray', 'door'], ['stray', 'door'], ['stray', 'door'], ['stray', 'door'],
    ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'],
    ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'],
    ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'],
    ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'],
    ['modmonster', 'door'], ['modmonster', 'door'], ['modmonster', 'door'], ['levelup', 'prize'],
    ['modmonster', 'door'], ['modmonster', 'door'], ['modmonster', 'door'], ['modmonster', 'door'],
    ['levelup', 'prize'], ['modmonster', 'door'], ['modmonster', 'door'],
    ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'],
    ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'],
    ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'],
    ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'],
    ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'],
    ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'],
    ['flash', 'prize', 'rags'], ['flash', 'boom', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'big', 'prize', 'rags'],
    ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['weapon', 'big', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['weapon', 'big', 'prize', 'rags'], ['weapon', 'prize', 'rags'], ['weapon', 'prize', 'rags'],
    ['closing', 'prize', 'rags'], ['closing', 'prize', 'rags'], ['closing', 'prize', 'rags'], ['closing', 'prize', 'rags'],
    ['closing', 'prize', 'rags'], ['closing', 'armor', 'prize', 'rags'], ['closing', 'boots', 'prize', 'rags'],
    ['closing', 'armor', 'prize', 'rags'], ['closing', 'big', 'armor', 'prize', 'rags'], ['closing', 'armor', 'prize', 'rags'],
    ['closing', 'boots', 'prize', 'rags'], ['closing', 'boots', 'prize', 'rags'], ['closing', 'boots', 'prize', 'rags'],
    ['closing', 'big', 'armor', 'prize', 'rags'], ['closing', 'armor', 'prize', 'rags'], ['closing', 'boots', 'prize', 'rags'],
    ['closing', 'big', 'armor', 'prize', 'rags'], ['closing', 'big', 'armor', 'prize', 'rags'], ['closing', 'hat', 'prize', 'rags'],
    ['closing', 'hat', 'prize', 'rags'], ['closing', 'hat', 'prize', 'rags'], ['closing', 'hat', 'prize', 'rags'],
    ['closing', 'hat', 'prize', 'rags'], ['closing', 'hat', 'prize', 'rags'],
    ['mod', 'prize', 'rags'], ['mod', 'prize', 'rags'], ['mod', 'prize', 'rags'], ['mod', 'prize', 'rags'],
    ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'],
    ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'],
    ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'], ['prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'],
    ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags'], ['trash', 'prize', 'rags']
];
