<?php

return [
    ['class', 'stranger', 'door', 'male'], ['class', 'stranger', 'door', 'male'],
    ['class', 'stranger', 'door', 'female'], ['class', 'stranger', 'door', 'male'],
    ['class', 'paladin', 'door', 'male'], ['class', 'paladin', 'door', 'female'],
    ['class', 'paladin', 'door', 'male'], ['class', 'paladin', 'door', 'male'],
    ['class', 'raider', 'door', 'male'], ['class', 'raider', 'door', 'male'],
    ['class', 'raider', 'door', 'male'], ['class', 'raider', 'door', 'female'],
    ['class', 'scientist', 'door', 'male'], ['class', 'scientist', 'door', 'male'],
    ['class', 'scientist', 'door', 'female'], ['class', 'scientist', 'door', 'male'],
    ['trap', 'door'], ['trap', 'door'], ['trap', 'door'], ['trap', 'door'], ['trap','door'],
    ['trap', 'door'], ['trap', 'door'], ['trap', 'door'], ['trap', 'door'], ['trap', 'door'],
    ['trap', 'door'], ['trap', 'door'], ['trap', 'door'],
    ['monster', 'door'], ['monster', 'alien', 'door'], ['monster', 'swamp', 'door'], ['monster', 'gul', 'door'], ['monster', 'ant', 'door'], ['monster', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'gul', 'door'], ['monster', 'door'], ['monster', 'door'],
    ['monster', 'door'], ['monster', 'door'], ['monster', 'claw', 'door'], ['monster', 'claw', 'door'], ['monster', 'swamp', 'door'], ['monster', 'door'],
    ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'ant', 'door'], ['monster', 'door'],
    ['monster', 'door'], ['monster', 'ant', 'door'], ['monster', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'],
    ['monster', 'door'], ['monster', 'door'], ['monster', 'tarakan', 'door'], ['monster', 'robot', 'door'], ['monster', 'robot', 'door'], ['monster', 'robot', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'gul', 'door'], ['monster', 'door'], ['monster', 'mutant', 'door'], ['monster', 'mutant', 'door'], ['monster', 'mutant', 'door'],
    ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'robot', 'door'], ['monster', 'door'], ['monster', 'alien', 'door'], ['monster', 'swamp', 'door'],
    ['monster', 'door'], ['monster', 'door'],
    ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'], ['partner', 'door'],
    ['vats', 'door'], ['vats', 'door'],
    ['stray', 'door'], ['stray', 'door'], ['stray', 'door'], ['stray', 'door'], ['stray', 'door'],
    ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'], ['door'],
    ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'],
    ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'], ['radiation', 'door'],
    ['modmonster', 'door'], ['modmonster', 'door'], ['modmonster', 'door'], ['levelup', 'prize'], ['modmonster', 'door'], ['modmonster', 'door'],
    ['modmonster', 'door'], ['modmonster', 'door'], ['levelup', 'prize'], ['modmonster', 'door'], ['modmonster', 'door'],
    ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'],
    ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'], ['perk'],
    ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'],
    ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'], ['levelup', 'prize'],
    ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'],
    ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'], ['flash', 'boom', 'prize'], ['flash', 'prize'], ['flash', 'boom', 'prize'],
    ['weapon', 'small', 'prize'], ['weapon', 'energy', 'prize'], ['weapon', 'energy', 'prize'], ['weapon', 'small', 'prize'], ['weapon', 'big', 'prize'],
    ['weapon', 'energy', 'prize'], ['weapon', 'small', 'prize'], ['weapon', 'energy', 'prize'], ['weapon', 'big', 'prize'], ['weapon', 'cold', 'prize'],
    ['weapon', 'energy', 'prize'], ['weapon', 'energy', 'prize'], ['weapon', 'cold', 'prize'], ['weapon', 'big', 'prize'], ['weapon', 'energy', 'prize'],
    ['weapon', 'big', 'prize'], ['weapon', 'cold', 'prize'], ['weapon', 'big', 'prize'], ['weapon', 'small', 'prize'], ['weapon', 'cold', 'prize'],
    ['closing', 'prize'], ['closing', 'prize'], ['closing', 'prize'], ['closing', 'prize'], ['closing', 'prize'],
    ['closing', 'armor', 'prize'], ['closing', 'boots', 'prize'], ['closing', 'armor', 'prize'], ['closing', 'big', 'armor', 'prize'], ['closing', 'armor', 'prize'],
    ['closing', 'boots', 'prize'], ['closing', 'boots', 'prize'], ['closing', 'boots', 'prize'], ['closing', 'big', 'armor', 'prize'], ['closing', 'armor', 'prize'],
    ['closing', 'boots', 'prize'], ['closing', 'big', 'armor', 'prize'], ['closing', 'big', 'armor', 'prize'], ['closing', 'hat', 'prize'], ['closing', 'hat', 'prize'],
    ['closing', 'hat', 'prize'], ['closing', 'hat', 'prize'], ['closing', 'hat', 'prize'], ['closing', 'hat', 'prize'],
    ['mod', 'prize'], ['mod', 'prize'], ['mod', 'prize'], ['mod', 'prize'],
    ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'],
    ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'],
    ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'], ['prize'],
    ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'],
    ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'],
    ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize'], ['trash', 'prize']
];
